name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init Terraform/sns/main.tf

      - name: Terraform Plan
        run: terraform plan ./Terraform/sns/main.tf

      # - name: Terraform Apply
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve -var-file=./terraform/terraform.tfvars ./terraform



# name: "terraform-plan"

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:
#     inputs:
#       working-dir:
#         type: multi-choice
#         description: select the working directory
#         options: 
#         - sns
#         - sqs
  

# jobs:
#   PushToAWS:
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_REGION: ${{ secrets.AWS_REGION }}


#     steps:
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#         with:
#           terraform_version: 0.14.4

#       - name: Terraform Fmt
#         id: fmt
#         run: terraform fmt -check
#         continue-on-error: true
#         working-directory: ${{ github.event.inputs.working-dir }}
      
#       - name: Terraform init
#         id: init
#         run: terraform init
#         working-directory: ${{ github.event.inputs.working-dir }}


      
      # - name: Terraform Init
      #   id: init
      #   run: |
      #     terraform fmt
      #     terraform validate
      #     terraform init ${{ github.event.inputs.working-dir }}

      # - name: Terraform plan
      #   id: plan
      #   run: |
      #     echo ${{ github.event.inputs.working-dir }}
      #     terraform plan ${{ github.event.inputs.working-dir }}

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     TF_VAR_aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
      #     TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      #     TF_VAR_jwtSecret: ${{ secrets.JWT_SECRET }}
